### ISSUE TITLE
GreenKubo_analyze for alkanes

### ISSUE THREAD

**Issue by ramess101** [ramess101/IFPSC_10#2]
Email from @mostafa-razavi :

When I run GreenKubo_analyze.py I get this error:

mostafa@mostafa:~/Git/IFPSC_10/C4H10/Gromacs/Mie_16_Bayesian_Viscosity_200_MCMC$ python ~/Git/IFPSC_10/Scripts/GreenKubo_analyze.py 

Traceback (most recent call last):
  File "/home/mostafa/Git/IFPSC_10/Scripts/GreenKubo_analyze.py", line 1343, in <module>
    main()   
  File "/home/mostafa/Git/IFPSC_10/Scripts/GreenKubo_analyze.py", line 1330, in main
    MCMC_Mie = GreenKubo_MCMC(args.ilow,args.ihigh)
  File "/home/mostafa/Git/IFPSC_10/Scripts/GreenKubo_analyze.py", line 53, in __init__
    self.base_path_all = self.gen_base_path()
  File "/home/mostafa/Git/IFPSC_10/Scripts/GreenKubo_analyze.py", line 379, in gen_base_path
    for iMCMC in np.arange(ilow,ihigh+1):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

I have a few questions:

1- Does the current version of GreenKubo_analyze.py work for n-butane as it is? If not, what changes should I make?

2- How (using what command-line arguments) should I run GreenKubo_analyze.py? What directory should I run this script in?

**Comment by ramess101** [comment]
My response:

1.	No, the current version of GreenKubo_analyze.py only gets meaningful results for ethane. For example, currently the temperatures and experimental values are hardcoded. I will make these changes today. However, that is not why you are getting this error. If you scroll to the bottom of nAlkanes_Bayesian… you will see:

cd "$output_path" || exit

###GreenKubo_analyze for all MCMC parameter sets
python "$scripts_path"/GreenKubo_analyze.py --ilow 0 --ihigh $((NREP_low-1)) --nReps 1 --irho "$j" –sat

This shows that you need to provide –ilow 0 –ihigh 199 –nReps 1 –irho “$j” -sat as arguments to the script. ilow and ihigh just say the range of MCMC parameter sets (0-199, 200 folders), nReps is how many reps at each parameter set (just 1, I used to use more than 1), irho is the density index (you should have a rho0, rho1, rho2, rho3, rho4) and -sat is just a flag to say this is a saturation condition. I will improve the documentation in GreenKubo to make this more clear.

2.	As shown above, you need to cd into “$output_path”, which is 

output_path=~/"$Compound"/Gromacs/"$Model"

in general, and for your specific case should be: 

~/C4H10/Gromacs/Mie_16_Bayesian_Viscosity_200_MCMC/

You need to run the previous command once for each irho value, i.e. j=0-4. My script does that each time it loops around.

**Comment by ramess101** [comment]
My response:

So the GreenKublo_analyze code actually does work for any compound, in that it will properly estimate the viscosity (although I need to modify it for more reliable estimates at high viscosities). The only problem before was the plot with respect to temperature that compares simulation to REFPROP and experimental values (TDE). In other words, I needed to modify GreenKubo_analyze so that it reads in the actual simulation temperatures. This required some small modifications in the nAlkanes… script, specifically, you need SaturatedSettings.txt to be found in the “$output_path” directory.
